name: Deploy to Azure VM

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          script: |
            cd ~/AZURE
            git pull origin main
            npm install @whiskeysockets/baileys@latest
            npm install
            pm2 restart bmm || pm2 start src/index.js --name bmm
            # Wait for the bot to fully initialize
            sleep 60
            # Send update notifications with the correct version
            node scripts/notifyUpdate.js
